### ISSUE TITLE
android sdk里面updateVideoImage方法执行无效

### ISSUE THREAD

**Issue by droidsde** [VideoCloudTeam/Android-SDK#1]
执行完
        vcrtc.updateVideoImage(((MeetingActivity) getActivity()).closeVideoBitmap);
        vcrtc.setVideoEnable(isMuteVideo, true);
对方机器只是画面卡住了，没有更新为updateVideoImage设置的图片

**Comment by 6YingJie** [comment]
要使用VCRTCPreferences的setImageFilePath方法设置一张初始图片。
VCRTCPreferences prefs = new VCRTCPreferences(context);
prefs.setImageFilePath(imagePath);
